### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by Easyleoo** [liwenju0/cutword#2]
Traceback (most recent call last):
  File "cutword.py", line 116, in <module>
    res = tokenizer.cutword(text)
  File "cutword.py", line 105, in cutword
    res.extend(self._tokenize(blk))
  File "cutword.py", line 87, in _tokenize
    if score > scores[e]:
IndexError: list index out of range
请问如何解决？

**Comment by liwenju0** [comment]
可以把测试的例子给一下吗
